#!/usr/bin/env python3
"""Generate the browsable HTML mirror of the Symphony Framework documentation."""

from __future__ import annotations

import argparse
import html
import os
import re
import sys
import urllib.parse
from dataclasses import dataclass, field
from pathlib import Path


WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = WORKSPACE_ROOT / "Assets" / "SymphonyFrameWork"
DOCUMENTATION_ROOT = PACKAGE_ROOT / "Documentation~"
MODULES_ROOT = DOCUMENTATION_ROOT / "Modules"
HTML_ROOT = DOCUMENTATION_ROOT / "Html"
INDEX_OUTPUT = HTML_ROOT / "index.html"

GENERATED_MARKER = "Generated by scripts/build_module_docs.py"

# 各モジュール文書をindexへ並べる順。README・AGENTS.mdの導線と同じ順序にする。
MODULE_ORDER = (
    "ServiceLocator",
    "SceneLoader",
    "SaveDataSystem",
    "AudioManager",
    "PauseManager",
    "Debug",
    "Utility",
    "InspectorAttributes",
    "AutoEnumGenerator",
    "AssetStoreToolsPackager",
    "ProjectStructureTools",
)

LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
CODE_SPAN_PATTERN = re.compile(r"`([^`]+)`")
BOLD_PATTERN = re.compile(r"\*\*(.+?)\*\*")
HEADING_PATTERN = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
FENCE_PATTERN = re.compile(r"^\s*```\s*([^\s`]*)\s*$")
BULLET_PATTERN = re.compile(r"^(\s*)-\s+(.*)$")
ORDERED_PATTERN = re.compile(r"^(\s*)(\d+)\.\s+(.*)$")
TABLE_DIVIDER_PATTERN = re.compile(r"^\s*\|(?:\s*:?-{2,}:?\s*\|)+\s*$")
RULE_PATTERN = re.compile(r"^-{3,}\s*$")
PLACEHOLDER_PATTERN = re.compile("\x00(\\d+)\x00")

# 対応表に無い記法。見つけたら生成を止める。黙って素通しすると生成HTMLだけが静かに壊れる。
UNSUPPORTED_PATTERNS = (
    (re.compile(r"!\["), "画像"),
    (re.compile(r"<[a-zA-Z/!]"), "生のHTMLタグまたは自動リンク"),
    (re.compile(r"\]\["), "参照リンク"),
    (re.compile(r"~~"), "打ち消し線"),
    (re.compile(r"\[\^"), "脚注"),
    (re.compile(r"(?<!\*)\*(?!\*)"), "1つの`*`による強調"),
    (re.compile(r"(?<!\w)_[^_\s][^_]*_(?!\w)"), "`_`による強調"),
)

STYLE = """
:root {
  color-scheme: light dark;
  --bg: #ffffff;
  --fg: #1f2328;
  --muted: #59636e;
  --border: #d1d9e0;
  --code-bg: #f6f8fa;
  --link: #0969da;
  --accent: #8250df;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0d1117;
    --fg: #e6edf3;
    --muted: #9198a1;
    --border: #3d444d;
    --code-bg: #161b22;
    --link: #4493f8;
    --accent: #ab7df8;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0 auto;
  padding: 2rem 1.25rem 6rem;
  max-width: 56rem;
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, "Segoe UI", "Hiragino Sans", "Noto Sans JP", Meiryo, sans-serif;
  line-height: 1.75;
  overflow-wrap: anywhere;
}
nav.doc-nav {
  margin-bottom: 2rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid var(--border);
  font-size: 0.875rem;
  color: var(--muted);
}
nav.doc-nav a { color: var(--link); }
h1, h2, h3, h4, h5, h6 { line-height: 1.35; margin: 2.25rem 0 0.75rem; }
h1 { font-size: 1.9rem; margin-top: 0; }
h2 { font-size: 1.45rem; padding-bottom: 0.3rem; border-bottom: 1px solid var(--border); }
h3 { font-size: 1.2rem; }
h4, h5, h6 { font-size: 1.05rem; }
a { color: var(--link); }
p, ul, ol { margin: 0.75rem 0; }
li { margin: 0.3rem 0; }
li > p:first-child { margin-top: 0; }
li > p:last-child { margin-bottom: 0; }
hr { margin: 2.5rem 0; border: 0; border-top: 1px solid var(--border); }
code {
  padding: 0.15em 0.35em;
  background: var(--code-bg);
  border-radius: 6px;
  font-family: ui-monospace, "Cascadia Mono", Consolas, "Noto Sans Mono", monospace;
  font-size: 0.9em;
}
pre {
  margin: 1rem 0;
  padding: 0.9rem 1rem;
  background: var(--code-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow-x: auto;
  line-height: 1.55;
}
pre code { padding: 0; background: none; font-size: 0.85rem; }
pre.mermaid-source::before {
  content: "mermaid";
  display: block;
  margin-bottom: 0.5rem;
  color: var(--accent);
  font-size: 0.75rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.table-scroll { margin: 1rem 0; overflow-x: auto; }
table { border-collapse: collapse; min-width: 100%; }
th, td { padding: 0.45rem 0.75rem; border: 1px solid var(--border); text-align: left; vertical-align: top; }
th { background: var(--code-bg); white-space: nowrap; }
.module-list { padding-left: 1.2rem; }
.source-note { margin-top: 3rem; color: var(--muted); font-size: 0.8rem; }
"""


class DocumentError(Exception):
    """正本のMarkdownが対応範囲を超えている、または参照先が壊れている。"""

    def __init__(self, source: Path, line: int, message: str) -> None:
        location = source.relative_to(WORKSPACE_ROOT).as_posix()
        super().__init__(f"{location}:{line}: {message}")


@dataclass
class Document:
    source: Path
    output: Path
    title: str = ""
    slugs: set[str] = field(default_factory=set)
    heading_slugs: list[str] = field(default_factory=list)


def collect_documents() -> list[Document]:
    """変換対象を決める。Documentation~/Html/ 自身とAGENTS.mdは対象外。"""
    sources: list[Path] = [PACKAGE_ROOT / "README.md", PACKAGE_ROOT / "CHANGELOG.md"]
    sources += sorted(DOCUMENTATION_ROOT.glob("*.md"))
    sources += sorted(MODULES_ROOT.glob("*.md"))

    documents = []
    for source in sources:
        if source.parent == MODULES_ROOT:
            output = HTML_ROOT / "Modules" / f"{source.stem}.html"
        else:
            output = HTML_ROOT / f"{source.stem}.html"
        documents.append(Document(source=source.resolve(), output=output.resolve()))
    return documents


def slugify(text: str) -> str:
    """GitHubと同じ規則で見出しのidを作る。"""
    plain = CODE_SPAN_PATTERN.sub(r"\1", text)
    plain = LINK_PATTERN.sub(r"\1", plain)
    plain = BOLD_PATTERN.sub(r"\1", plain)
    plain = plain.strip().lower()
    plain = re.sub(r"[^\w\s-]", "", plain, flags=re.UNICODE)
    return re.sub(r"\s+", "-", plain.strip())


def iterate_content_lines(text: str) -> list[tuple[int, str]]:
    """行番号付きの行を返す。フェンス内かどうかの判定は呼び出し側で行う。"""
    return list(enumerate(text.splitlines(), start=1))


def index_headings(document: Document) -> None:
    """見出しのidを確定し、重複には連番を付ける。"""
    text = document.source.read_text(encoding="utf-8")
    inside_fence = False
    assigned: dict[str, int] = {}

    for _, line in iterate_content_lines(text):
        if FENCE_PATTERN.match(line):
            inside_fence = not inside_fence
            continue
        if inside_fence:
            continue

        match = HEADING_PATTERN.match(line)
        if not match:
            continue

        base = slugify(match.group(2))
        count = assigned.get(base, 0)
        assigned[base] = count + 1
        slug = base if count == 0 else f"{base}-{count}"
        document.heading_slugs.append(slug)
        document.slugs.add(slug)

        if not document.title and len(match.group(1)) == 1:
            document.title = CODE_SPAN_PATTERN.sub(r"\1", match.group(2))

    if not document.title:
        document.title = document.source.stem


class Renderer:
    def __init__(self, document: Document, registry: dict[Path, Document]) -> None:
        self._document = document
        self._registry = registry
        self._heading_index = 0

    # ------------------------------------------------------------------ inline

    def render_inline(self, text: str, line: int) -> str:
        # コードスパンを除いた本文へ先に掛ける。`<T...>` や `<color>` を誤検知しないため。
        self.reject_unsupported(CODE_SPAN_PATTERN.sub("", text), line)

        placeholders: list[str] = []

        def store(fragment: str) -> str:
            placeholders.append(fragment)
            return f"\x00{len(placeholders) - 1}\x00"

        def replace_link(match: re.Match[str]) -> str:
            href = self.rewrite_link(match.group(2).strip(), line)
            label = self.render_inline(match.group(1), line)
            return store(f'<a href="{html.escape(href, quote=True)}">{label}</a>')

        rendered = LINK_PATTERN.sub(replace_link, text)
        rendered = CODE_SPAN_PATTERN.sub(
            lambda match: store(f"<code>{html.escape(match.group(1))}</code>"), rendered
        )

        rendered = html.escape(rendered)
        rendered = BOLD_PATTERN.sub(r"<strong>\1</strong>", rendered)
        if "**" in rendered:
            raise DocumentError(self._document.source, line, "閉じていない`**`があります")

        return PLACEHOLDER_PATTERN.sub(
            lambda match: placeholders[int(match.group(1))], rendered
        )

    def reject_unsupported(self, text: str, line: int) -> None:
        for pattern, label in UNSUPPORTED_PATTERNS:
            if pattern.search(text):
                raise DocumentError(
                    self._document.source,
                    line,
                    f"未対応の記法です（{label}）。対応記法は scripts/build_module_docs.py の"
                    " UNSUPPORTED_PATTERNS とREADMEを参照してください",
                )

    def rewrite_link(self, target: str, line: int) -> str:
        if target.startswith(("http://", "https://", "mailto:")):
            return target

        path_part, _, fragment = target.partition("#")

        if not path_part:
            self.assert_anchor(self._document, fragment, line, target)
            return f"#{fragment}"

        resolved = (self._document.source.parent / urllib.parse.unquote(path_part)).resolve()

        if not resolved.exists():
            raise DocumentError(
                self._document.source, line, f"リンク先が存在しません: {target}"
            )

        if resolved in self._registry:
            destination = self._registry[resolved]
            self.assert_anchor(destination, fragment, line, target)
            relative = self.relative_to_output(destination.output)
            return f"{relative}#{fragment}" if fragment else relative

        if resolved == MODULES_ROOT.resolve():
            # モジュール文書のディレクトリを指すリンクは、生成物側では索引へ寄せる。
            return self.relative_to_output(INDEX_OUTPUT.resolve())

        # 変換対象外（LICENSE.txt、Samples/Runtime など）は出力位置からの相対パスへ直す。
        return self.relative_to_output(resolved)

    def assert_anchor(
        self, destination: Document, fragment: str, line: int, target: str
    ) -> None:
        if fragment and fragment not in destination.slugs:
            raise DocumentError(
                self._document.source, line, f"アンカーが見つかりません: {target}"
            )

    def relative_to_output(self, path: Path) -> str:
        return os.path.relpath(path, self._document.output.parent).replace("\\", "/")

    # ------------------------------------------------------------------- blocks

    def render_document(self) -> str:
        lines = iterate_content_lines(self._document.source.read_text(encoding="utf-8"))
        body = self.render_blocks(lines)
        return self.wrap(body)

    def render_blocks(self, lines: list[tuple[int, str]]) -> str:
        parts: list[str] = []
        index = 0

        while index < len(lines):
            line_number, raw = lines[index]

            if not raw.strip():
                index += 1
                continue

            fence = FENCE_PATTERN.match(raw)
            if fence:
                index = self.render_code_block(lines, index, fence.group(1), parts)
                continue

            heading = HEADING_PATTERN.match(raw)
            if heading:
                level = len(heading.group(1))
                slug = self.next_slug()
                content = self.render_inline(heading.group(2), line_number)
                parts.append(f'<h{level} id="{html.escape(slug, quote=True)}">{content}</h{level}>')
                index += 1
                continue

            if RULE_PATTERN.match(raw.strip()) and not raw.startswith(" "):
                parts.append("<hr />")
                index += 1
                continue

            if raw.strip().startswith("|"):
                index = self.render_table(lines, index, parts)
                continue

            if BULLET_PATTERN.match(raw) or ORDERED_PATTERN.match(raw):
                index = self.render_list(lines, index, parts)
                continue

            index = self.render_paragraph(lines, index, parts)

        return "\n".join(parts)

    def render_code_block(
        self, lines: list[tuple[int, str]], index: int, language: str, parts: list[str]
    ) -> int:
        start_line = lines[index][0]
        index += 1
        collected: list[str] = []

        while index < len(lines):
            if FENCE_PATTERN.match(lines[index][1]):
                index += 1
                break
            collected.append(lines[index][1])
            index += 1
        else:
            raise DocumentError(
                self._document.source, start_line, "コードブロックが閉じていません"
            )

        classes = ["mermaid-source"] if language == "mermaid" else []
        attribute = f' class="{" ".join(classes)}"' if classes else ""
        code_class = f' class="language-{html.escape(language, quote=True)}"' if language else ""
        body = html.escape("\n".join(collected))
        parts.append(f"<pre{attribute}><code{code_class}>{body}</code></pre>")
        return index

    def render_table(
        self, lines: list[tuple[int, str]], index: int, parts: list[str]
    ) -> int:
        header_line, header_raw = lines[index]

        if index + 1 >= len(lines) or not TABLE_DIVIDER_PATTERN.match(lines[index + 1][1]):
            raise DocumentError(
                self._document.source, header_line, "テーブルに区切り行がありません"
            )

        header_cells = self.split_row(header_raw)
        index += 2
        rows: list[tuple[int, list[str]]] = []

        while index < len(lines) and lines[index][1].strip().startswith("|"):
            rows.append((lines[index][0], self.split_row(lines[index][1])))
            index += 1

        head = "".join(
            f"<th>{self.render_inline(cell, header_line)}</th>" for cell in header_cells
        )
        body = "".join(
            "<tr>"
            + "".join(f"<td>{self.render_inline(cell, line)}</td>" for cell in cells)
            + "</tr>"
            for line, cells in rows
        )
        parts.append(
            '<div class="table-scroll"><table>'
            f"<thead><tr>{head}</tr></thead><tbody>{body}</tbody>"
            "</table></div>"
        )
        return index

    @staticmethod
    def split_row(raw: str) -> list[str]:
        stripped = raw.strip()
        if stripped.startswith("|"):
            stripped = stripped[1:]
        if stripped.endswith("|"):
            stripped = stripped[:-1]
        return [cell.strip() for cell in stripped.split("|")]

    def render_list(
        self, lines: list[tuple[int, str]], index: int, parts: list[str]
    ) -> int:
        ordered = ORDERED_PATTERN.match(lines[index][1]) is not None
        pattern = ORDERED_PATTERN if ordered else BULLET_PATTERN
        indent = len(pattern.match(lines[index][1]).group(1))
        items: list[str] = []

        while index < len(lines):
            raw = lines[index][1]

            if not raw.strip():
                # 次の非空行が同じリストの続きでなければ、そこでリストを閉じる。
                lookahead = index + 1
                while lookahead < len(lines) and not lines[lookahead][1].strip():
                    lookahead += 1
                if lookahead >= len(lines):
                    break
                following = lines[lookahead][1]
                continues = len(following) - len(following.lstrip()) > indent
                if not continues and not self.starts_item(following, pattern, indent):
                    break
                index = lookahead
                continue

            match = pattern.match(raw)
            if match is None or len(match.group(1)) != indent:
                break

            content_lines: list[tuple[int, str]] = [
                (lines[index][0], match.group(3 if ordered else 2))
            ]
            index += 1

            while index < len(lines):
                candidate = lines[index][1]
                if not candidate.strip():
                    lookahead = index + 1
                    while lookahead < len(lines) and not lines[lookahead][1].strip():
                        lookahead += 1
                    if lookahead >= len(lines):
                        break
                    following = lines[lookahead][1]
                    if len(following) - len(following.lstrip()) <= indent:
                        break
                    content_lines.append((lines[index][0], ""))
                    index += 1
                    continue
                if len(candidate) - len(candidate.lstrip()) <= indent:
                    break
                content_lines.append((lines[index][0], candidate))
                index += 1

            items.append(self.render_list_item(content_lines))

        tag = "ol" if ordered else "ul"
        parts.append(f"<{tag}>" + "".join(f"<li>{item}</li>" for item in items) + f"</{tag}>")
        return index

    @staticmethod
    def starts_item(raw: str, pattern: re.Pattern[str], indent: int) -> bool:
        match = pattern.match(raw)
        return match is not None and len(match.group(1)) == indent

    def render_list_item(self, content_lines: list[tuple[int, str]]) -> str:
        continuation = [line for line in content_lines[1:] if line[1].strip()]
        if continuation:
            shift = min(len(raw) - len(raw.lstrip()) for _, raw in continuation)
        else:
            shift = 0

        normalized = [content_lines[0]] + [
            (number, raw[shift:] if raw.strip() else "")
            for number, raw in content_lines[1:]
        ]

        rendered = self.render_blocks(normalized)
        single_paragraph = rendered.startswith("<p>") and rendered.count("<p>") == 1
        if single_paragraph and rendered.endswith("</p>"):
            return rendered[3:-4]
        return rendered

    def render_paragraph(
        self, lines: list[tuple[int, str]], index: int, parts: list[str]
    ) -> int:
        start_line = lines[index][0]
        collected: list[str] = []

        while index < len(lines):
            raw = lines[index][1]
            if not raw.strip():
                break
            if FENCE_PATTERN.match(raw) or HEADING_PATTERN.match(raw):
                break
            if raw.strip().startswith("|") or RULE_PATTERN.match(raw.strip()):
                break
            if BULLET_PATTERN.match(raw) or ORDERED_PATTERN.match(raw):
                break
            collected.append(raw.strip())
            index += 1

        text = " ".join(collected) if len(collected) > 1 else collected[0]
        parts.append(f"<p>{self.render_inline(text, start_line)}</p>")
        return index

    # -------------------------------------------------------------------- page

    def next_slug(self) -> str:
        slug = self._document.heading_slugs[self._heading_index]
        self._heading_index += 1
        return slug

    def wrap(self, body: str) -> str:
        source_relative = self._document.source.relative_to(WORKSPACE_ROOT).as_posix()
        index_href = self.relative_to_output(INDEX_OUTPUT.resolve())
        navigation = (
            "" if self._document.output == INDEX_OUTPUT.resolve()
            else f'<nav class="doc-nav"><a href="{index_href}">Symphony Framework Documentation</a></nav>'
        )
        return render_page(
            title=self._document.title,
            source_relative=source_relative,
            navigation=navigation,
            body=body,
        )


def render_page(title: str, source_relative: str, navigation: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<!-- {GENERATED_MARKER} from {source_relative}. Do not edit. -->
<html lang="ja">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{html.escape(title)} — Symphony Framework</title>
<style>{STYLE}</style>
</head>
<body>
{navigation}
{body}
<p class="source-note">この文書は <code>{html.escape(source_relative)}</code> から生成しています。編集は正本のMarkdownへ行ってください。</p>
</body>
</html>
"""


def render_index(documents: list[Document]) -> str:
    by_stem = {document.source.stem: document for document in documents}

    def item(document: Document, note: str = "") -> str:
        href = os.path.relpath(document.output, HTML_ROOT).replace("\\", "/")
        suffix = f" — {html.escape(note)}" if note else ""
        return f'<li><a href="{href}">{html.escape(document.title)}</a>{suffix}</li>'

    modules = "".join(
        item(by_stem[stem]) for stem in MODULE_ORDER if stem in by_stem
    )
    guides = "".join(
        item(by_stem[stem])
        for stem in ("README", "EditorTools", "Architecture", "Deprecations", "AgentUsage", "AgentVerification", "CHANGELOG")
        if stem in by_stem
    )

    body = (
        "<h1>Symphony Framework Documentation</h1>"
        "<p>モジュールごとの文書です。クイックスタート、実装時の注意、対応するEditor機能、"
        "内部構造が1ファイルにまとまっています。</p>"
        f'<h2 id="モジュール">モジュール</h2><ul class="module-list">{modules}</ul>'
        f'<h2 id="全体">全体</h2><ul class="module-list">{guides}</ul>'
        "<p>正本はMarkdownです。内容を直す場合は "
        "<code>Assets/SymphonyFrameWork/Documentation~/</code> のMarkdownを編集し、"
        "<code>python scripts/build_module_docs.py</code> で再生成してください。</p>"
    )
    return render_page(
        title="Symphony Framework Documentation",
        source_relative="Assets/SymphonyFrameWork/Documentation~/Modules/",
        navigation="",
        body=body,
    )


def build() -> dict[Path, str]:
    documents = collect_documents()
    for document in documents:
        index_headings(document)

    registry = {document.source: document for document in documents}
    rendered: dict[Path, str] = {}

    for document in documents:
        rendered[document.output] = Renderer(document, registry).render_document()

    rendered[INDEX_OUTPUT.resolve()] = render_index(documents)
    return rendered


def write(rendered: dict[Path, str]) -> int:
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")

    for stale in find_stale_outputs(rendered):
        stale.unlink()

    print(f"Generated {len(rendered)} HTML files under {HTML_ROOT.relative_to(WORKSPACE_ROOT)}")
    return 0


def find_stale_outputs(rendered: dict[Path, str]) -> list[Path]:
    if not HTML_ROOT.exists():
        return []
    expected = set(rendered)
    return sorted(
        path.resolve()
        for path in HTML_ROOT.rglob("*.html")
        if path.resolve() not in expected
    )


def check() -> list[str]:
    """生成物が正本と一致しているかを検証し、問題を文字列で返す。"""
    rendered = build()
    problems: list[str] = []

    for path, text in rendered.items():
        relative = path.relative_to(WORKSPACE_ROOT).as_posix()
        if not path.exists():
            problems.append(f"生成物がありません: {relative}")
        elif path.read_text(encoding="utf-8") != text:
            problems.append(f"生成物が正本と一致しません: {relative}")

    for stale in find_stale_outputs(rendered):
        problems.append(
            f"正本の無い生成物が残っています: {stale.relative_to(WORKSPACE_ROOT).as_posix()}"
        )

    return problems


def run_check() -> int:
    problems = check()
    if problems:
        print("ドキュメントHTMLが正本と同期していません:", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        print("python scripts/build_module_docs.py を実行してください。", file=sys.stderr)
        return 1

    print(f"OK: {len(build())}件の生成物が正本と同期しています")
    return 0


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(
        description="Assets/SymphonyFrameWork/ のMarkdownから Documentation~/Html/ を生成する。"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="生成せず、既存の生成物が正本と一致しているかだけ検証する。",
    )
    args = parser.parse_args()

    try:
        return run_check() if args.check else write(build())
    except DocumentError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
