#!/usr/bin/env python3
"""Synchronize Claude Code skill locators with canonical Agent Skills."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
CANONICAL_SKILLS_ROOT = WORKSPACE_ROOT / ".agents" / "skills"
CLAUDE_SKILLS_ROOT = WORKSPACE_ROOT / ".claude" / "skills"
LOCATOR_MARKER = (
    "<!-- Generated by scripts/sync_agent_skill_locators.py. "
    "Edit the canonical skill under .agents/skills instead. -->"
)
CLAUDE_FORK_SKILLS = frozenset(
    {
        "uloop-execute-dynamic-code",
        "uloop-simulate-keyboard",
        "uloop-simulate-mouse-input",
        "uloop-simulate-mouse-ui",
    }
)


def extract_frontmatter(skill_path: Path) -> str:
    text = skill_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{skill_path} does not start with YAML frontmatter")

    try:
        closing_index = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(f"{skill_path} has no closing frontmatter delimiter") from error

    frontmatter = lines[: closing_index + 1]
    if not any(line.startswith("name:") for line in frontmatter):
        raise ValueError(f"{skill_path} frontmatter has no name")
    if not any(line.startswith("description:") for line in frontmatter):
        raise ValueError(f"{skill_path} frontmatter has no description")
    return "\n".join(frontmatter)


def render_locator(skill_name: str, canonical_skill: Path) -> str:
    frontmatter = extract_frontmatter(canonical_skill)
    if skill_name in CLAUDE_FORK_SKILLS:
        frontmatter = frontmatter.removesuffix("\n---") + "\ncontext: fork\n---"
    canonical_path = f".agents/skills/{skill_name}/SKILL.md"
    return f"""{frontmatter}

{LOCATOR_MARKER}

# Skill locator

Before taking task actions, read `{canonical_path}` completely and follow it as
the authoritative skill instructions. Resolve every relative path mentioned by
that file against `.agents/skills/{skill_name}/`, not this locator directory.
"""


def expected_locators() -> dict[Path, str]:
    if not CANONICAL_SKILLS_ROOT.is_dir():
        raise FileNotFoundError(f"Canonical skills root is missing: {CANONICAL_SKILLS_ROOT}")

    expected: dict[Path, str] = {}
    for skill_dir in sorted(CANONICAL_SKILLS_ROOT.iterdir()):
        canonical_skill = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or not canonical_skill.is_file():
            continue
        locator_path = CLAUDE_SKILLS_ROOT / skill_dir.name / "SKILL.md"
        expected[locator_path] = render_locator(skill_dir.name, canonical_skill)
    return expected


def find_stale_locator_dirs(expected: dict[Path, str]) -> list[Path]:
    expected_dirs = {path.parent.resolve() for path in expected}
    if not CLAUDE_SKILLS_ROOT.is_dir():
        return []

    stale: list[Path] = []
    for skill_dir in CLAUDE_SKILLS_ROOT.iterdir():
        locator = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or skill_dir.resolve() in expected_dirs:
            continue
        if locator.is_file() and LOCATOR_MARKER in locator.read_text(encoding="utf-8"):
            stale.append(skill_dir)
    return stale


def check() -> int:
    expected = expected_locators()
    problems: list[str] = []
    for locator_path, expected_text in expected.items():
        if not locator_path.is_file():
            problems.append(f"missing locator: {locator_path.relative_to(WORKSPACE_ROOT)}")
            continue
        actual_text = locator_path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual_text != expected_text:
            problems.append(f"stale locator: {locator_path.relative_to(WORKSPACE_ROOT)}")

    for stale_dir in find_stale_locator_dirs(expected):
        problems.append(f"orphan locator: {stale_dir.relative_to(WORKSPACE_ROOT)}")

    for legacy_root in (WORKSPACE_ROOT / ".codex" / "skills", WORKSPACE_ROOT / ".gemini" / "skills"):
        if legacy_root.exists():
            problems.append(
                f"legacy skill root remains: {legacy_root.relative_to(WORKSPACE_ROOT)}; "
                "Codex and Gemini discover .agents/skills directly"
            )

    if problems:
        print("Agent skill locator check failed:", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        return 1

    print(f"OK: {len(expected)} canonical skills and Claude locators are synchronized")
    return 0


def sync() -> int:
    expected = expected_locators()
    for locator_path, expected_text in expected.items():
        locator_path.parent.mkdir(parents=True, exist_ok=True)
        locator_path.write_text(expected_text, encoding="utf-8", newline="\n")

    for stale_dir in find_stale_locator_dirs(expected):
        locator = stale_dir / "SKILL.md"
        locator.unlink()
        stale_dir.rmdir()

    print(f"Synchronized {len(expected)} Claude skill locators")
    return check()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize .claude/skills locators with canonical .agents/skills."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify locators without changing files.",
    )
    args = parser.parse_args()
    return check() if args.check else sync()


if __name__ == "__main__":
    raise SystemExit(main())
